workaround: status check for matrix jobs

diff --git a/.github/workflows/backend.build.workflows.yml b/.github/workflows/backend.build.workflows.yml
--- a/.github/workflows/backend.build.workflows.yml
+++ b/.github/workflows/backend.build.workflows.yml
@@ -56,3 +56,16 @@ jobs:
       - run: npm i
       - name: Build ${{ matrix.service_name }}
         run: npm run app -- ${{ matrix.service_name }} build
+
+  # workaround: https://stackoverflow.com/questions/70275958/how-do-i-set-a-github-branch-protection-rule-based-on-the-success-or-failure-of
+  results:
+    runs-on: ubuntu-latest
+    needs: build-cloud-run-jobs
+    if: always()
+    steps:
+      - name: All tests ok
+        if: ${{ !(contains(needs.*.result, 'failure')) }}
+        run: exit 0
+      - name: Some tests failed
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
