🚀 Add update-streams app (#259)

diff --git a/.github/workflows/backend.build.workflows.yml b/.github/workflows/backend.build.workflows.yml
--- a/.github/workflows/backend.build.workflows.yml
+++ b/.github/workflows/backend.build.workflows.yml
@@ -43,9 +43,9 @@ jobs:
   build-cloud-run-jobs:
     strategy:
       matrix:
-        service_name: [pubsubhubbub, hololive/update-channels]
+        service_name: [hololive/update-channels, pubsubhubbub, update-streams]
     runs-on: ubuntu-latest
-    needs: [paths-filter]
+    needs: paths-filter
     if: ${{ needs.paths-filter.outputs.has-changes == 'true' }}
     steps:
       - uses: actions/checkout@v4
@@ -56,3 +56,19 @@ jobs:
       - run: npm i
       - name: Build ${{ matrix.service_name }}
         run: npm run app -- ${{ matrix.service_name }} build
+
+  # workaround: https://stackoverflow.com/questions/70275958/how-do-i-set-a-github-branch-protection-rule-based-on-the-success-or-failure-of
+  results:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: .
+    needs: [type-check-and-build-closed-api-server, build-cloud-run-jobs]
+    if: always()
+    steps:
+      - name: All tests ok
+        if: ${{ !(contains(needs.*.result, 'failure')) }}
+        run: exit 0
+      - name: Some tests failed
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
